# Generated by Django 4.1.6 on 2023-05-27 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nameSite', models.CharField(max_length=140)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestLost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplementary.course')),
            ],
        ),
        migrations.CreateModel(
            name='Supplementary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('workshop', models.BooleanField(default=False)),
                ('monitoring', models.BooleanField(default=False)),
                ('supplementaryDate', models.DateTimeField()),
                ('id_sitio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplementary.site')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplementary.student')),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplementary.testlost')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='id_monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplementary.monitor'),
        ),
        migrations.AddField(
            model_name='course',
            name='id_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplementary.teacher'),
        ),
    ]
