# Generated by Django 4.1.6 on 2023-05-27 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id_monitor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id_teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='id_course',
            field=models.ForeignKey(default='111', on_delete=django.db.models.deletion.CASCADE, to='supplementary.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
