# Generated by Django 4.1.6 on 2023-05-27 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary', '0002_remove_course_id_monitor_remove_course_id_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='supplementary',
            name='id_test',
        ),
        migrations.AddField(
            model_name='supplementary',
            name='id_course',
            field=models.ForeignKey(default='1111', on_delete=django.db.models.deletion.CASCADE, to='supplementary.course'),
        ),
    ]
